In [5]:
import pandas as pd
import numpy as np

data = pd.read_csv('housing.csv')



In [6]:
rm = data['RM']
lstat = data['LSTAT']
ptratio = data['PTRATIO']
medv = data['MEDV']

In [8]:
corr_rm = np.corrcoef(rm, medv)
print(corr_rm)

corr_lstat = np.corrcoef(lstat, medv)
print('\n', corr_lstat)

corr_ptratio = np.corrcoef(ptratio, medv)
print('\n', corr_ptratio)

[[1.         0.69720922]
 [0.69720922 1.        ]]

 [[ 1.         -0.76067006]
 [-0.76067006  1.        ]]

 [[ 1.        -0.5190335]
 [-0.5190335  1.       ]]


In [12]:
prices = data['MEDV']
features = data.drop('MEDV', axis = 1)
print(prices)

0      504000.0
1      453600.0
2      728700.0
3      701400.0
4      760200.0
5      602700.0
6      480900.0
7      569100.0
8      346500.0
9      396900.0
10     315000.0
11     396900.0
12     455700.0
13     428400.0
14     382200.0
15     417900.0
16     485100.0
17     367500.0
18     424200.0
19     382200.0
20     285600.0
21     411600.0
22     319200.0
23     304500.0
24     327600.0
25     291900.0
26     348600.0
27     310800.0
28     386400.0
29     441000.0
         ...   
459    350700.0
460    252000.0
461    306600.0
462    449400.0
463    483000.0
464    497700.0
465    525000.0
466    457800.0
467    432600.0
468    445200.0
469    401100.0
470    432600.0
471    319200.0
472    147000.0
473    170100.0
474    285600.0
475    422100.0
476    457800.0
477    514500.0
478    485100.0
479    413700.0
480    384300.0
481    445200.0
482    367500.0
483    352800.0
484    470400.0
485    432600.0
486    501900.0
487    462000.0
488    249900.0
Name: MEDV, Length: 489,