In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv('housing.csv')

data

RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
5    6.430   5.21     18.7  602700.0
6    6.012  12.43     15.2  480900.0
7    6.172  19.15     15.2  569100.0
8    5.631  29.93     15.2  346500.0
9    6.004  17.10     15.2  396900.0
10   6.377  20.45     15.2  315000.0
11   6.009  13.27     15.2  396900.0
12   5.889  15.71     15.2  455700.0
13   5.949   8.26     21.0  428400.0
14   6.096  10.26     21.0  382200.0
15   5.834   8.47     21.0  417900.0
16   5.935   6.58     21.0  485100.0
17   5.990  14.67     21.0  367500.0
18   5.456  11.69     21.0  424200.0
19   5.727  11.28     21.0  382200.0
20   5.570  21.02     21.0  285600.0
21   5.965  13.83     21.0  411600.0
22   6.142  18.72     21.0  319200.0
23   5.813  19.88     21.0  304500.0
24   5.924  16.30     21.0  327600.0
25   5.599  16.51     21.0  291900.0
26   5.813  14.81     21.0  348600.0
27   6.047  17.28     21.0  310800.0
28   6.495  12.80     21.0  386400.0
29   6.674  11.98     21.0  441000.0
..     ...    ...      ...       ...
459  6.484  18.68     20.2  350700.0
460  5.304  24.91     20.2  252000.0
461  6.185  18.03     20.2  306600.0
462  6.229  13.11     20.2  449400.0
463  6.242  10.74     20.2  483000.0
464  6.750   7.74     20.2  497700.0
465  7.061   7.01     20.2  525000.0
466  5.762  10.42     20.2  457800.0
467  5.871  13.34     20.2  432600.0
468  6.312  10.58     20.2  445200.0
469  6.114  14.98     20.2  401100.0
470  5.905  11.45     20.2  432600.0
471  5.454  18.06     20.1  319200.0
472  5.414  23.97     20.1  147000.0
473  5.093  29.68     20.1  170100.0
474  5.983  18.07     20.1  285600.0
475  5.983  13.35     20.1  422100.0
476  5.707  12.01     19.2  457800.0
477  5.926  13.59     19.2  514500.0
478  5.670  17.60     19.2  485100.0
479  5.390  21.14     19.2  413700.0
480  5.794  14.10     19.2  384300.0
481  6.019  12.92     19.2  445200.0
482  5.569  15.10     19.2  367500.0
483  6.027  14.33     19.2  352800.0
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]

In [18]:
rm = data['RM']
lstat = data['LSTAT']
ptratio = data['PTRATIO']
medv = data['MEDV']

In [21]:
corr_rm = np.corrcoef(rm, medv)
print(corr)

corr_lstat = np.corrcoef(lstat, medv)
print('\n', corr_lstat)

corr_ptratio = np.corrcoef(ptratio, medv)
print('\n', corr_ptratio)

[[1.         0.69720922]
 [0.69720922 1.        ]]

 [[ 1.         -0.76067006]
 [-0.76067006  1.        ]]

 [[ 1.        -0.5190335]
 [-0.5190335  1.       ]]
